# -*- coding: utf-8 -*-
"""MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qjuq3d6X0HZFQmo46dQRyWGOUuDGRtX0
"""

import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df=pd.read_csv('/content/mnist.csv')

df=df.dropna()

X=df.iloc[:,1:]
y=df.iloc[:,0]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=32)

"""##finding best parameters"""

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
svm=SVC()
parameters={'kernel': ['rbf', 'poly', 'linear'],
            'C': [1.0,2.0,3.0],
            'gamma': ['scale', 'auto'],

            'decision_function_shape': ['ovr', 'ovo'],
            'probability': [False],
            }
grid_model=GridSearchCV(estimator=svm,param_grid=parameters,cv=2,scoring='accuracy')
result=grid_model.fit(X_train,y_train)
result.best_params_



class MNIST():
  def __init__(self,path):
    try:
      self.path=path
      self.df=pd.read_csv(self.path)
      self.df=self.df.dropna()
      self.X=self.df.iloc[:,1:]
      self.y=self.df.iloc[:,0]
      self.X_train,self.X_test,self.y_train,self.y_test=train_test_split(self.X,self.y,test_size=0.3,random_state=42)
    except Exception as e:
       ex_type,ex_tb,ex_msg=sys.exc_info()
       print(f'issue is from {ex_tb.tb_lineno} due to {ex_msg}')
  def training(self):
    try:
      self.svm=SVC(C=3.0,decision_function_shape='ovr',gamma='scale',kernel='rbf',probability=False)
      self.svm.fit(self.X_train,self.y_train)
      print(f'train accuracy:{accuracy_score(self.y_train,self.svm.predict(self.X_train))}')
      print(f'classification report:{classification_report(self.y_train,self.svm.predict(self.X_train))}')
      print(f'confusion matrix:{confusion_matrix(self.y_train,self.svm.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_tb,ex_msg=sys.exc_info()
      print(f'issue is from {ex_tb.tb_lineno} due to {ex_msg}')

  def testing(self):
    try:
      print(f'test accuracy:{accuracy_score(self.y_test,self.svm.predict(self.X_test))}')
      print(f'classification report:{classification_report(self.y_test,self.svm.predict(self.X_test))}')
      print(f'confusion matrix:{confusion_matrix(self.y_test,self.svm.predict(self.X_test))}')
    except Exception as e:
      ex_type,ex_tb,ex_msg=sys.exc_info()
      print(f'issue is from {ex_tb.tb_lineno} due to {ex_msg}')

if __name__=='__main__':
  try:
    dataset_path=('/content/mnist.csv')
    obj=MNIST(dataset_path)
    obj.training()
    obj.testing()
  except Exception as e:
       ex_type,ex_tb,ex_msg=sys.exc_info()
       print(f'issue is from {ex_tb.tb_lineno} due to {ex_msg}')

import pickle
with open('MNIST.pkl','wb') as f:
  pickle.dump(obj.svm,f)

with open('MNIST.pkl','rb') as f:
  m=pickle.load(f)

import warnings
warnings.filterwarnings('ignore')

test_sample = np.random.randint(0, 256, size=(784,))
test_sample = test_sample.reshape(1, -1)
pred = m.predict(test_sample)
print(pred)