# -*- coding: utf-8 -*-
"""model_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Wu_PYaYMQwNxCRW9e-f3nr1FW57pKOo
"""



import sys
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,roc_auc_score,roc_curve
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt

!pip install xgboost

df=pd.read_csv('/content/mnist.csv')
df.dropna()
X=df.iloc[:,1:]
y=df.iloc[:,0]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

from xgboost import XGBClassifier

from sklearn.metrics import roc_curve, auc
class MODEL_SELECTION():
  def __init__(self,path):
    try:
      self.path=path
      self.df=pd.read_csv(self.path)
      self.df=self.df.dropna()
      self.X=self.df.iloc[:,1:]
      self.y=self.df.iloc[:,0]
      self.X_train,self.X_test,self.y_train,self.y_test=train_test_split(self.X,self.y,test_size=0.3,random_state=32)
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')

  def rf(self):
    try:
      self.rf=RandomForestClassifier(n_estimators=5,criterion='entropy')
      self.rf.fit(self.X_train,self.y_train)
      print(f'random forest accuracy {accuracy_score(self.y_train,self.rf.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')

  def knn(self):
    try:
      self.knn=KNeighborsClassifier()
      self.knn.fit(self.X_train,self.y_train)
      print(f'knn accuracy {accuracy_score(self.y_train,self.knn.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')


  def lr(self):
    try:
      self.lr=LogisticRegression()
      self.lr.fit(self.X_train,self.y_train)
      print(f'logistic regression {accuracy_score(self.y_train,self.lr.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')

  def dt(self):
    try:
      self.dt=DecisionTreeClassifier(criterion='entropy')
      self.dt.fit(self.X_train,self.y_train)
      print(f'decision tree {accuracy_score(self.y_train,self.dt.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')

  def nb(self):
    try:
      self.nb=GaussianNB()
      self.nb.fit(self.X_train,self.y_train)
      print(f'naive bayes {accuracy_score(self.y_train,self.nb.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')

  def ada(self):
    try:
      self.ada=AdaBoostClassifier(estimator=self.dt,n_estimators=100)
      self.ada.fit(self.X_train,self.y_train)
      print(f'adaboost {accuracy_score(self.y_train,self.ada.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')



  def xgb(self):
    try:
      self.xgb=XGBClassifier(n_estimators=50)
      self.xgb.fit(self.X_train,self.y_train)
      print(f'xtreme gradient boosting {accuracy_score(self.y_train,self.xgb.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')

  def svm(self):
    try:
      self.svm=SVC(kernel='rbf')
      self.svm.fit(self.X_train,self.y_train)
      print(f'svm {accuracy_score(self.y_train,self.svm.predict(self.X_train))}')
    except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')

  def roc(self):
    try:
        from sklearn.metrics import roc_curve, auc
        plt.figure(figsize=(10,6))

        self.classes = sorted(list(set(self.y_test)))


        if len(self.classes) > 2:
            self.y_test_bin = label_binarize(self.y_test, classes=self.classes)


        svm_prob = SVC(probability=True)
        svm_prob.fit(self.X_train, self.y_train)

        models = {
            "Random Forest": self.rf.predict_proba(self.X_test),
            "KNN": self.knn.predict_proba(self.X_test),
            "Logistic Regression": self.lr.predict_proba(self.X_test),
            "Decision Tree": self.dt.predict_proba(self.X_test),
            "Naive Bayes": self.nb.predict_proba(self.X_test),
            "AdaBoost": self.ada.predict_proba(self.X_test),
            "XGBoost": self.xgb.predict_proba(self.X_test),
            "SVM": svm_prob.predict_proba(self.X_test),
        }


        if len(self.classes) == 2:
            for model_name, pred in models.items():
                fpr, tpr, _ = roc_curve(self.y_test, pred[:,1])
                auc_score = auc(fpr, tpr)
                plt.plot(fpr, tpr, label=f"{model_name} (AUC={auc_score:.3f})")

            plt.plot([0,1],[0,1],'k--')

        else:
            for model_name, pred in models.items():
                fpr, tpr, _ = roc_curve(self.y_test_bin.ravel(), pred.ravel())
                auc_score = auc(fpr, tpr)
                plt.plot(fpr, tpr, label=f"{model_name} (AUC={auc_score:.3f})")

        plt.xlabel("False Positive Rate")
        plt.ylabel("True Positive Rate")
        plt.title("ROC Curve")
        plt.legend()
        plt.show()

    except Exception as e:
        ex_type, ex_line, ex_msg = sys.exc_info()
        print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')



if __name__=='__main__':
  try:
    dataset_path='/content/mnist.csv'
    obj=MODEL_SELECTION(dataset_path)
    obj.rf()
    obj.knn()
    obj.lr()
    obj.nb()
    obj.dt()
    obj.ada()
    obj.xgb()
    obj.svm()
    obj.roc()
  except Exception as e:
      ex_type,ex_line,ex_msg=sys.exc_info()
      print(f'issue is from {ex_line.tb_lineno} due to {ex_msg}')